### ISSUE TITLE
It is hard for me to install through your instruction

### ISSUE THREAD

**Issue by ld9866** [shilpagarg/DipAsm#24]
Could l use this command to install the docker environment?
docker pull luhancheng/dipasm
Is there a difference between these ways?
It is hard for me to install through your instruction.
Thank you!

**Comment by ld9866** [comment]
When l print ‘bash test.sh | bash“ , it showed that , althouth l have tried to install this model through pip, it still can not work and  show the same worse.
Thanky you!

Peregrine Assembler & SHIMMER ASMKit(1.6.3+3.g008082a)
Traceback (most recent call last):
  File "/opt/conda/envs/peregrine/bin/pg_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('peregrine==1.6.3+3.g008082a', 'pg_run.py')
  File "/opt/conda/envs/peregrine/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/envs/peregrine/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/envs/peregrine/lib/python3.7/site-packages/peregrine-1.6.3+3.g008082a-py3.7-linux-x86_64.egg/EGG-INFO/scripts/pg_run.py", line 2, in <module>
    from pypeflow.simple_pwatcher_bridge import (PypeProcWatcherWorkflow, Dist)
ModuleNotFoundError: No module named 'pypeflow'
